### ISSUE TITLE
annotation files from CelebA dataset is no longer in csv format 

### ISSUE THREAD

**Issue by nina-weng** [guillaumejs2403/DiME#3]
Hi there,
Thank you for open sourcing your code!!
I have noticed that on CelebA webpage, they now only provide the .txt files as the annotation ([link](https://mmlab.ie.cuhk.edu.hk/projects/CelebA.html)). Not sure if I missed the csv files anywhere on the CelebA website, if so, could you please let me know how to find it? 
Otherwise, is that okay if I just simply convert the txt to csv if I wanna reproduce the sampling process? Or could you provide the csv files as well? 

Best,
Nina

**Comment by guillaumejs2403** [comment]
Hi Nina,

Maybe I changed it, or it was a csv when I downloaded it long ago. Just replace the ".txt" with ".csv" and it should work. Please let me know if it did.

**Comment by nina-weng** [comment]
Hi! I delete the first line of the attribution annotation file (the first line is just one number 202599, not as a part of the table) and convert it to csv using pandas. And it works.

**Comment by guillaumejs2403** [comment]
Cool! Thanks remarking this problem :)
