### ISSUE TITLE
l1_loss and l2_loss

### ISSUE THREAD

**Issue by oceanzwq** [guillaumejs2403/DiME#4]
Hi，

Thanks for the open source code! 
I read the paper carefully and found that the loss function is divided into two parts: Lclass and Lperc. Do they correspond to l2_loss and l1_loss respectively in main.py? If so, where are the definitions of l2_loss and l1_loss in the code? 

Thank you very much for your answer!

**Comment by guillaumejs2403** [comment]
Hi @oceanzwq,

For the classification loss $L_{class}$, use the `classifier_scales` flag. For the perceptual loss $L_{perc}$, use the `l_perc` flag. Additionally, we have implemented a $\ell_1$ loss (see the implementation details for more info). The `l1_loss` flag refers to this loss. The `l2_loss` is similar to the `l1_loss` but uses the $\ell_2$ instead.

**Comment by oceanzwq** [comment]
Thank you very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "guillaumejs2403/DiME"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月27日(星期三) 下午5:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [guillaumejs2403/DiME] l1_loss and l2_loss (Issue #4)





 
Hi @oceanzwq,
 
For the classification loss $L_{class}$, use the classifier_scales flag. For the perceptual loss $L_{perc}$, use the l_perc flag. Additionally, we have implemented a $\ell_1$ loss (see the implementation details for more info). The l1_loss flag refers to this loss. The l2_loss is similar to the l1_loss but uses the $\ell_2$ instead.
